import { User, HotspotReport, CleanupEvent, Product, EducationalPost, FarmTelemetry, Sponsor, LeaderboardEntry, B2BService, Notification, PlatformStats, MapPin } from '@/types';

export const currentUser: User = {
  id: 'u1', name: 'Alex Greenfield', email: 'alex@greenduty.eco', avatarUrl: '/images/avatar.svg', role: 'citizen', points: 2450,
  badges: ['Eco-Warrior', 'Tree-Planter', 'Top-Reporter'], joinedAt: '2024-03-15T10:00:00Z',
  location: { lat: 40.7128, lng: -74.006, address: 'New York, NY' },
  farmDetails: { farmName: 'Greenfield Acres', size: 120, crops: ['Organic Wheat', 'Soy', 'Corn'], certifications: ['USDA Organic', 'Non-GMO'] }
};

export const users: User[] = [
  currentUser,
  { id: 'u2', name: 'Maria Santos', email: 'maria@ecofarm.org', avatarUrl: '/images/avatar.svg', role: 'farmer', points: 3200, badges: ['Master-Grower', 'Soil-Saver'], joinedAt: '2024-01-10T08:00:00Z', farmDetails: { farmName: 'Santos Organic', size: 85, crops: ['Tomatoes', 'Peppers', 'Herbs'], certifications: ['USDA Organic'] } },
  { id: 'u3', name: 'Dr. James Chen', email: 'james@agronomist.org', avatarUrl: '/images/avatar.svg', role: 'agronomist', points: 1800, badges: ['Green-Certifier'], joinedAt: '2024-02-20T09:00:00Z' },
  { id: 'u4', name: 'GreenEarth Corp', email: 'info@greenearth.com', avatarUrl: '/images/avatar.svg', role: 'corporate', points: 15000, badges: ['Platinum-Sponsor'], joinedAt: '2024-01-05T07:00:00Z', companyDetails: { companyName: 'GreenEarth Corp', industry: 'Manufacturing', csrBudget: 500000, website: 'https://greenearth.com' } },
  { id: 'u5', name: 'EcoWatch NGO', email: 'contact@ecowatch.org', avatarUrl: '/images/avatar.svg', role: 'ngo', points: 8900, badges: ['Community-Organizer'], joinedAt: '2024-01-01T00:00:00Z' },
  { id: 'u6', name: 'Admin GreenDuty', email: 'admin@greenduty.eco', avatarUrl: '/images/avatar.svg', role: 'admin', points: 0, badges: [], joinedAt: '2023-12-01T00:00:00Z' },
];
export const hotspotReports: HotspotReport[] = [
  { id: 'h1', title: 'Plastic Waste Dump near Riverbank', description: 'Large accumulation of plastic waste along the East River bank. Approx 200 sq meters affected.', location: { lat: 40.7282, lng: -73.9749, address: 'East River Park, NYC' }, severity: 'severe', status: 'event_created', imageUrl: '', reporterId: 'u1', reporterName: 'Alex Greenfield', pollutionType: 'plastics', createdAt: '2025-06-10T14:30:00Z', updatedAt: '2025-06-12T09:00:00Z', upvotes: 34 },
  { id: 'h2', title: 'Chemical Runoff in Farmland Creek', description: 'Suspected chemical fertilizer runoff turning creek water green. Dead fish observed.', location: { lat: 40.6892, lng: -74.0445, address: 'Jersey City, NJ' }, severity: 'critical', status: 'reported', imageUrl: '', reporterId: 'u2', reporterName: 'Maria Santos', pollutionType: 'chemical_waste', createdAt: '2025-06-18T08:15:00Z', updatedAt: '2025-06-18T08:15:00Z', upvotes: 27 },
  { id: 'h3', title: 'Illegal Dumping Site - Construction Debris', description: 'Construction debris illegally dumped in protected woodland area.', location: { lat: 40.7482, lng: -73.9957, address: 'Central Park North, NYC' }, severity: 'moderate', status: 'in_progress', imageUrl: '', reporterId: 'u5', reporterName: 'EcoWatch NGO', pollutionType: 'illegal_dumping', createdAt: '2025-05-28T11:00:00Z', updatedAt: '2025-06-15T16:30:00Z', upvotes: 19 },
  { id: 'h4', title: 'Deforestation Spot - Urban Development', description: 'Trees being cleared for new construction without proper permits.', location: { lat: 40.7831, lng: -73.9712, address: 'Upper West Side, NYC' }, severity: 'severe', status: 'reported', imageUrl: '', reporterId: 'u1', reporterName: 'Alex Greenfield', pollutionType: 'deforestation', createdAt: '2025-06-20T07:45:00Z', updatedAt: '2025-06-20T07:45:00Z', upvotes: 42 },
  { id: 'h5', title: 'Water Pollution - Industrial Discharge', description: 'Dark colored discharge from industrial pipe into the Hudson River.', location: { lat: 40.7052, lng: -74.0132, address: 'Hudson River, Battery Park' }, severity: 'critical', status: 'reported', imageUrl: '', reporterId: 'u5', reporterName: 'EcoWatch NGO', pollutionType: 'water_pollution', createdAt: '2025-06-22T13:00:00Z', updatedAt: '2025-06-22T13:00:00Z', upvotes: 56 },
  { id: 'h6', title: 'Air Pollution Near School', description: 'Factory emissions causing smog near elementary school. Parents concerned.', location: { lat: 40.7349, lng: -74.0715, address: 'Newark, NJ' }, severity: 'severe', status: 'reported', imageUrl: '', reporterId: 'u1', reporterName: 'Alex Greenfield', pollutionType: 'air_pollution', createdAt: '2025-06-25T09:30:00Z', updatedAt: '2025-06-25T09:30:00Z', upvotes: 38 },
  { id: 'h7', title: 'Soil Contamination - Old Landfill', description: 'Former landfill site showing signs of soil contamination. Heavy metals detected.', location: { lat: 40.6389, lng: -74.1127, address: 'Staten Island, NY' }, severity: 'moderate', status: 'cleaned', imageUrl: '', reporterId: 'u5', reporterName: 'EcoWatch NGO', pollutionType: 'soil_contamination', createdAt: '2025-05-10T10:00:00Z', updatedAt: '2025-06-01T14:00:00Z', upvotes: 15 },
  { id: 'h8', title: 'Plastic Pollution at Beach Shore', description: 'Microplastics and larger debris washed up along popular beach area.', location: { lat: 40.5728, lng: -73.9852, address: 'Coney Island Beach, NY' }, severity: 'moderate', status: 'event_created', imageUrl: '', reporterId: 'u2', reporterName: 'Maria Santos', pollutionType: 'plastics', createdAt: '2025-06-15T16:00:00Z', updatedAt: '2025-06-17T11:00:00Z', upvotes: 23 },
];

export const mapPins: MapPin[] = hotspotReports.map(h => ({ id: h.id, lat: h.location.lat, lng: h.location.lng, severity: h.severity, title: h.title, pollutionType: h.pollutionType, status: h.status }));

export const cleanupEvents: CleanupEvent[] = [
  { id: 'e1', title: 'East River Plastic Cleanup Drive', description: 'Community cleanup of plastic waste at East River Park. Gloves and bags provided.', hotspotId: 'h1', location: { lat: 40.7282, lng: -73.9749, address: 'East River Park, NYC' }, date: '2025-07-15T09:00:00Z', volunteerCount: 23, maxVolunteers: 50, sponsorId: 'u4', sponsorName: 'GreenEarth Corp', rewardPoints: 150, status: 'upcoming', imageUrl: '', treeCount: 50 },
  { id: 'e2', title: 'Coney Island Beach Restoration', description: 'Beach cleanup and microplastic collection event.', hotspotId: 'h8', location: { lat: 40.5728, lng: -73.9852, address: 'Coney Island Beach, NY' }, date: '2025-07-20T08:00:00Z', volunteerCount: 15, maxVolunteers: 40, rewardPoints: 120, status: 'upcoming', imageUrl: '', treeCount: 30 },
  { id: 'e3', title: 'Woodland Debris Removal', description: 'Removing illegally dumped construction debris from protected woodland.', hotspotId: 'h3', location: { lat: 40.7482, lng: -73.9957, address: 'Central Park North, NYC' }, date: '2025-07-08T09:00:00Z', volunteerCount: 12, maxVolunteers: 25, sponsorId: 'u4', sponsorName: 'GreenEarth Corp', rewardPoints: 200, status: 'upcoming', imageUrl: '', treeCount: 100 },
  { id: 'e4', title: 'Staten Island Soil Remediation', description: 'Soil treatment and native plant restoration at former landfill.', hotspotId: 'h7', location: { lat: 40.6389, lng: -74.1127, address: 'Staten Island, NY' }, date: '2025-07-05T08:30:00Z', volunteerCount: 35, maxVolunteers: 35, rewardPoints: 250, status: 'completed', imageUrl: '', treeCount: 200 },
];
export const products: Product[] = [
  { id: 'p1', name: 'Organic Heirloom Tomato Seeds', description: 'Non-GMO heirloom tomato seeds. 10 varieties included.', category: 'seeds', price: 1800, currency: 'DZD', stock: 500, qualityCertified: true, organicCertified: true, sellerId: 'u2', sellerName: 'Santos Organic Farm', sellerVerified: true, images: [], rating: 4.8, reviewCount: 127, warrantyMonths: 0, createdAt: '2025-01-15T08:00:00Z', features: ['Non-GMO', 'Heirloom', '10 varieties'] },
  { id: 'p2', name: 'Smart Drip Irrigation Kit', description: 'Automated drip irrigation with soil moisture sensors and WiFi controller.', category: 'irrigation', price: 25000, currency: 'DZD', stock: 45, qualityCertified: true, organicCertified: false, sellerId: 'u2', sellerName: 'AgriTech Solutions', sellerVerified: true, images: [], rating: 4.6, reviewCount: 89, warrantyMonths: 24, createdAt: '2025-02-01T10:00:00Z', features: ['WiFi Enabled', 'Soil Sensors', 'Auto-Scheduling', 'Rain Delay'] },
  { id: 'p3', name: 'Organic Bio-Fertilizer 5L', description: 'Liquid bio-fertilizer with beneficial microorganisms. 100% organic.', category: 'fertilizers', price: 3400, currency: 'DZD', stock: 200, qualityCertified: true, organicCertified: true, sellerId: 'u2', sellerName: 'Santos Organic Farm', sellerVerified: true, images: [], rating: 4.7, reviewCount: 203, warrantyMonths: 0, createdAt: '2025-01-20T09:00:00Z', features: ['Nitrogen-Fixing', 'Organic', 'Concentrated'] },
  { id: 'p4', name: 'IoT Soil Sensor Array', description: 'Professional-grade soil sensor measuring pH, moisture, temperature, and NPK.', category: 'sensors', price: 47000, currency: 'DZD', stock: 18, qualityCertified: true, organicCertified: false, sellerId: 'u2', sellerName: 'AgriTech Solutions', sellerVerified: true, images: [], rating: 4.9, reviewCount: 56, warrantyMonths: 36, createdAt: '2025-03-01T11:00:00Z', features: ['pH Sensor', 'Moisture', 'Temperature', 'NPK', 'Solar Powered'] },
  { id: 'p5', name: 'Organic Green Wheatgrass Powder', description: 'Freshly harvested organic wheatgrass powder. 500g resealable pack.', category: 'organic_produce', price: 2600, currency: 'DZD', stock: 150, qualityCertified: true, organicCertified: true, sellerId: 'u2', sellerName: 'Santos Organic Farm', sellerVerified: true, images: [], rating: 4.5, reviewCount: 78, warrantyMonths: 0, createdAt: '2025-04-10T07:00:00Z', features: ['Cold Pressed', 'Nutrient Rich', 'Resealable Pack'] },
  { id: 'p6', name: 'Neem Oil Bio-Pesticide', description: 'Cold-pressed neem oil for natural pest control. Safe for edible crops.', category: 'bio_pesticides', price: 2200, currency: 'DZD', stock: 300, qualityCertified: true, organicCertified: true, sellerId: 'u2', sellerName: 'Santos Organic Farm', sellerVerified: true, images: [], rating: 4.4, reviewCount: 145, warrantyMonths: 0, createdAt: '2025-02-15T08:30:00Z', features: ['100% Natural', 'Safe for Bees', 'Broad Spectrum'] },
  { id: 'p7', name: 'Pruning Tool Set (Professional)', description: 'Professional-grade pruning set with ergonomic handles and stainless steel blades.', category: 'tools', price: 6200, currency: 'DZD', stock: 80, qualityCertified: false, organicCertified: false, sellerId: 'u2', sellerName: 'FarmTools Pro', sellerVerified: true, images: [], rating: 4.3, reviewCount: 234, warrantyMonths: 12, createdAt: '2025-01-05T08:00:00Z', features: ['Ergonomic', 'Stainless Steel', '5-Piece Set'] },
  { id: 'p8', name: 'Automated Greenhouse Controller', description: 'Complete climate control system for greenhouses with IoT monitoring.', category: 'smart_farming', price: 175000, currency: 'DZD', stock: 10, qualityCertified: true, organicCertified: false, sellerId: 'u2', sellerName: 'AgriTech Solutions', sellerVerified: true, images: [], rating: 5.0, reviewCount: 32, warrantyMonths: 36, createdAt: '2025-03-15T09:00:00Z', features: ['Temperature Control', 'Humidity', 'Ventilation', 'App Control', 'AI Optimized'] },
];

export const educationalPosts: EducationalPost[] = [
  { id: 'ep1', title: '5 Principles of Regenerative Agriculture', content: 'Regenerative agriculture focuses on restoring soil health through minimal tillage, cover cropping, crop rotation, composting, and managed grazing...', excerpt: 'Learn the core principles that make regenerative agriculture a solution for climate change and food security.', status: 'certified', authorId: 'u3', authorName: 'Dr. James Chen', authorRole: 'agronomist', reviewerId: 'u6', reviewerName: 'Admin GreenDuty', tags: ['regenerative', 'soil-health', 'sustainability'], sourceVerified: true, createdAt: '2025-05-10T10:00:00Z', reviewedAt: '2025-05-11T09:30:00Z', likes: 234, comments: 45 },
  { id: 'ep2', title: 'Advanced Composting Techniques for Small Farms', content: 'Composting is the backbone of organic soil management. This guide explores hot composting, vermicomposting, and bokashi methods...', excerpt: 'Transform farm waste into black gold with these proven composting methods.', status: 'certified', authorId: 'u3', authorName: 'Dr. James Chen', authorRole: 'agronomist', tags: ['composting', 'soil-fertility', 'organic-farming'], sourceVerified: true, createdAt: '2025-05-15T14:00:00Z', reviewedAt: '2025-05-16T11:00:00Z', likes: 189, comments: 32 },
  { id: 'ep3', title: 'Water Conservation Through Smart Irrigation', content: 'Smart irrigation systems can reduce water usage by up to 40% while improving crop yields...', excerpt: 'Cut water usage by 40% while boosting yields with smart irrigation technology.', status: 'certified', authorId: 'u3', authorName: 'Dr. James Chen', authorRole: 'agronomist', tags: ['irrigation', 'water-conservation', 'smart-farming'], sourceVerified: true, createdAt: '2025-06-01T09:00:00Z', reviewedAt: '2025-06-02T08:00:00Z', likes: 156, comments: 28 },
  { id: 'ep4', title: 'Understanding Soil Microbiomes', content: 'The soil microbiome is a complex ecosystem of bacteria, fungi, and microorganisms...', excerpt: 'Dive into the hidden world beneath our feet.', status: 'pending', authorId: 'u1', authorName: 'Alex Greenfield', authorRole: 'citizen', tags: ['soil-science', 'microbiology'], sourceVerified: false, createdAt: '2025-06-20T16:00:00Z', likes: 67, comments: 12 },
  { id: 'ep5', title: 'Integrated Pest Management (IPM) Strategies', content: 'IPM combines biological, cultural, physical, and chemical tools to minimize risks...', excerpt: 'A holistic approach to pest control that minimizes chemical use.', status: 'certified', authorId: 'u3', authorName: 'Dr. James Chen', authorRole: 'agronomist', reviewerId: 'u6', reviewerName: 'Admin GreenDuty', tags: ['pest-management', 'ipm', 'sustainable'], sourceVerified: true, createdAt: '2025-06-05T11:00:00Z', reviewedAt: '2025-06-06T10:00:00Z', likes: 201, comments: 39 },
  { id: 'ep6', title: 'Carbon Sequestration in Agricultural Soils', content: 'Agricultural soils can sequester significant amounts of atmospheric CO2...', excerpt: 'How farming can be a climate solution through carbon-smart soil management.', status: 'pending', authorId: 'u1', authorName: 'Alex Greenfield', authorRole: 'citizen', tags: ['carbon', 'climate', 'soil-health'], sourceVerified: false, createdAt: '2025-06-22T13:00:00Z', likes: 45, comments: 8 },
];
export const farmTelemetry: FarmTelemetry[] = [
  { id: 't1', farmId: 'f1', farmName: 'Greenfield Acres', soilMoisture: 62, temperature: 24.5, humidity: 68, irrigationStatus: 'scheduled', waterFlowRate: 12.5, lastWatered: '2025-06-25T06:00:00Z', nextSchedule: '2025-06-26T06:00:00Z', pumpStatus: 'idle', ph: 6.8, nutrientLevel: 75, lastUpdated: '2025-06-25T14:00:00Z' },
  { id: 't2', farmId: 'f2', farmName: 'Santos Organic', soilMoisture: 45, temperature: 26.8, humidity: 55, irrigationStatus: 'on', waterFlowRate: 18.2, lastWatered: '2025-06-25T07:00:00Z', nextSchedule: '2025-06-25T19:00:00Z', pumpStatus: 'running', ph: 6.5, nutrientLevel: 82, lastUpdated: '2025-06-25T14:05:00Z' },
  { id: 't3', farmId: 'f3', farmName: 'Valley View Farm', soilMoisture: 78, temperature: 22.1, humidity: 72, irrigationStatus: 'off', waterFlowRate: 0, lastWatered: '2025-06-24T18:00:00Z', nextSchedule: '2025-06-26T06:00:00Z', pumpStatus: 'idle', ph: 7.0, nutrientLevel: 65, lastUpdated: '2025-06-25T12:00:00Z' },
  { id: 't4', farmId: 'f4', farmName: 'Sunrise Organics', soilMoisture: 35, temperature: 29.2, humidity: 48, irrigationStatus: 'on', waterFlowRate: 22.1, lastWatered: '2025-06-25T05:30:00Z', nextSchedule: '2025-06-25T17:30:00Z', pumpStatus: 'running', ph: 6.2, nutrientLevel: 55, lastUpdated: '2025-06-25T14:10:00Z' },
];

export const sponsors: Sponsor[] = [
  { id: 's1', name: 'GreenEarth Corp', logoUrl: '', tier: 'platinum', totalSponsored: 250000, eventsSponsored: 12, treesPlanted: 5000 },
  { id: 's2', name: 'EcoTech Industries', logoUrl: '', tier: 'gold', totalSponsored: 150000, eventsSponsored: 8, treesPlanted: 3000 },
  { id: 's3', name: 'CleanFuture Ltd', logoUrl: '', tier: 'silver', totalSponsored: 75000, eventsSponsored: 5, treesPlanted: 1500 },
  { id: 's4', name: 'BioSphere Partners', logoUrl: '', tier: 'bronze', totalSponsored: 25000, eventsSponsored: 3, treesPlanted: 500 },
];

export const leaderboard: LeaderboardEntry[] = [
  { userId: 'u2', userName: 'Maria Santos', avatarUrl: '/images/avatar.svg', points: 3200, eventsAttended: 18, hotspotsReported: 12, rank: 1 },
  { userId: 'u1', userName: 'Alex Greenfield', avatarUrl: '/images/avatar.svg', points: 2450, eventsAttended: 14, hotspotsReported: 9, rank: 2 },
  { userId: 'u5', userName: 'EcoWatch NGO', avatarUrl: '/images/avatar.svg', points: 8900, eventsAttended: 25, hotspotsReported: 20, rank: 3 },
];

export const b2bServices: B2BService[] = [
  { id: 'b1', name: 'Custom Farm Dashboard', description: 'Tailored web dashboard for real-time farm monitoring, analytics, and team management.', category: 'dashboard', priceRange: '$5,000 - $25,000', deliveryTime: '4-6 weeks', features: ['Real-time analytics', 'Multi-user', 'Custom reports', 'API integration'], icon: 'LayoutDashboard' },
  { id: 'b2', name: 'IoT Greenhouse System', description: 'End-to-end smart greenhouse with sensors, actuators, and cloud monitoring.', category: 'iot', priceRange: '$15,000 - $75,000', deliveryTime: '8-12 weeks', features: ['Temperature control', 'Automated ventilation', 'Soil monitoring', 'Mobile alerts'], icon: 'Thermometer' },
  { id: 'b3', name: 'Agri-Tech Web Platform', description: 'Custom web apps for farm e-commerce, supply chain, and marketplace solutions.', category: 'web_dev', priceRange: '$10,000 - $50,000', deliveryTime: '6-10 weeks', features: ['E-commerce', 'Inventory', 'Payments', 'Order tracking'], icon: 'Globe' },
  { id: 'b4', name: 'Irrigation Automation', description: 'Smart irrigation system with weather-based scheduling and zone controls.', category: 'automation', priceRange: '$8,000 - $40,000', deliveryTime: '3-6 weeks', features: ['Weather integration', 'Zone controls', 'Water reports', 'Remote access'], icon: 'Droplets' },
  { id: 'b5', name: 'Agronomy Consulting', description: 'Expert consulting for sustainable farming, crop optimization, and soil management.', category: 'consulting', priceRange: '$2,000 - $15,000', deliveryTime: '2-4 weeks', features: ['Soil analysis', 'Crop planning', 'Sustainability audit', 'Training'], icon: 'Sprout' },
];

export const notifications: Notification[] = [
  { id: 'n1', userId: 'u1', title: 'Cleanup Event Tomorrow!', message: 'East River Cleanup is tomorrow at 9 AM. Don\'t forget your gloves!', type: 'event', read: false, createdAt: '2025-07-14T10:00:00Z', link: '/eco-map' },
  { id: 'n2', userId: 'u1', title: 'Post Under Review', message: 'Your article "Soil Microbiomes" is pending agronomist verification.', type: 'post', read: false, createdAt: '2025-06-21T09:00:00Z', link: '/feed' },
  { id: 'n3', userId: 'u1', title: '150 Points Earned!', message: 'You earned 150 reward points for reporting a pollution hotspot!', type: 'reward', read: true, createdAt: '2025-06-20T15:00:00Z' },
  { id: 'n4', userId: 'u1', title: 'Order Shipped!', message: 'Your Smart Drip Irrigation Kit has been shipped!', type: 'order', read: false, createdAt: '2025-06-22T11:00:00Z', link: '/marketplace' },
];

export const platformStats: PlatformStats = { treesPlanted: 12750, hotspotsCleaned: 342, activeFarmers: 2841, co2Offset: 12500, waterSaved: 8500000, eventsHosted: 89, certifiedPosts: 156, productsSold: 4520 };
